### ISSUE TITLE
eta

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#10]
In the prototype SimulatedUniverse, line 127 uses eta to select the fraction of stars that will have planets:
# Map planets to target stars
probs = np.random.uniform(size=TL.nStars)
self.plan2star = np.where(probs > self.eta)[0]

when I set eta=1, there are no planets.
When i set eta=0, all the stars have planets.

The traditional definition of eta is the fraction of stars with planets, so I would expect the reverse behavior for planet selection given eta.  I recommend the following correction to line 127 to flip the inequality:
self.plan2star = np.where(probs < self.eta)[0]

**Comment by dsavransky** [comment]
Okay.  Latest commit fully moves eta to the PlanetPopulation module (since its solely a population concept) and updates the ICD accordingly.  The gen_planetary_systems method in the SimulatedUniverse prototype has been updated to treat PlanetPopulation.eta as the rate parameter of a poisson distribution, and the number of planets per target is now drawn from this distribution.  Note that this means that even if \eta < 1, targets are not guaranteed to have a maximum of one planet.  If this behavior is desired, we can add a different implementation of the SimulatedUniverse to accommodate this (start a new issue for that, if needed).
