### ISSUE TITLE
Nemati calc_dMag_per_intTime has a hardcoded dMagLim value of 25

### ISSUE THREAD

**Issue by walker-dula** [dsavransky/EXOSIMS#162]
On line 133 of Nemati, dMagLim is calculated like so:

`dMagLim = np.zeros(len(sInds)) + 25`

We would like this value to actually reflect the dMagLim set in the script file for the given simulation.

For example:

`dMagLim = np.zeros(len(sInds)) + TL.Completness.dMagLim`

**Comment by dsavransky** [comment]
The value of dMagLim in this line has no effect on the calculation.  It is set only because we are reusing Cp_Cb_Csp in this method, and that requires a dMagLim input.  If you look at the next line, only  C_b and C_sp are actually returned - the C_p value (the only thing that is impacted by the dMagLim input) is discarded.

**Comment by deanthedream** [comment]
This informaciton should be added as a comment.
