### ISSUE TITLE
Silent Error in SurveySimulation: observation_detection

### ISSUE THREAD

**Issue by walker-dula** [dsavransky/EXOSIMS#37]
Around line 632 in SurveySimulation, there is a line of code that fails silently when it is called:

```
WA = np.random.uniform(mode['IWA'].to('mas'), np.minimum(mode['OWA'], \
                    np.arctan(max(PPop.arange)/TL.dist[sInd])).to('mas'))
```

`np.random.uniform()` cannot handle astropy quantities, and will return a -1 and an error when it is attempted. See the test case below as an example:

```
x = 1*u.m
y = 5*u.m
np.random.uniform(x,y)

-1.0

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/units/quantity.py", line 1073, in __float__
    raise TypeError('Only dimensionless scalar quantities can be '
TypeError: Only dimensionless scalar quantities can be converted to Python scalars
```

While an error is raised, the simulation will continue to run using WA = -1, causing further problems down the line.

One simple solution is the following:

```
WA = np.random.uniform(mode['IWA'].to('mas').value, np.minimum(mode['OWA'], \
                    np.arctan(max(PPop.arange)/TL.dist[sInd])).to('mas').value)
```

Which remedies the problem without any further changes necessary.

**Comment by ChrisDelaX** [comment]
@walker-dula: Thanks Walker, I will implement your solution.
This bug is very unusual because it works perfectly fine on my machine.
`In [1]: import numpy as np

In [2]: import astropy.units as u

In [3]: x = 1*u.m; y = 5*u.m; x, y
Out[3]: (<Quantity 1.0 m>, <Quantity 5.0 m>)

In [4]: np.random.uniform(x, y)
Out[4]: array(2.0566112312421345)

In [5]: np.random.uniform(1*u.mas, 5*u.mas)
Out[5]: array(4.860140000230423)
`
I'm using Python version 2.7.13, Astropy version 1.3.2, Numpy version 1.11.2
Could you tell me which versions you were using to generate this error?

**Comment by walker-dula** [comment]
That is strange. I am using:
Python 2.7.13
numpy 1.12.1
astropy 1.3.1
scipy 0.19.0

It sounds like the issue is version specific to either astropy or numpy. I updated my version of astropy to 1.3.3, but the problem persisted, which makes me think that the issue must lie in numpy.

**Comment by ChrisDelaX** [comment]
I just updated numpy and the error showed up.
```
In [1]: import numpy as np

In [2]: import astropy.units as u

In [3]: np.random.uniform(1*u.m, 5*u.m)
Out[3]: -1.0
```

Thanks for your help. Your bugfix will appear in my next push. Closing this issue.
