### ISSUE TITLE
Find a better way to handle integration time multipliers

### ISSUE THREAD

**Issue by ChrisDelaX** [dsavransky/EXOSIMS#57]

**Comment by dsavransky** [comment]
More details so we don't forget what this meant:  currently, if integration time multiplier is greater than 1, all of the checks on visibility, SNR, etc. occur on just the initial observation, and then additional time due to the multiplier is arbitrarily tacked onto the end of the observation.  Ideally, all of these tests should be done on the additional integration time represented by the multiplier.

**Comment by deanthedream** [comment]
Dmitry, we haven't had any discussion on how this would be implemented and has never been made priority. The ICD has a clear description of what this is supposed to be.

**Comment by dsavransky** [comment]
Not relevant to current integration time calculation.
