### ISSUE TITLE
CpCb attenuation

### ISSUE THREAD

**Issue by rhondamorgan** [dsavransky/EXOSIMS#9]
in prototype OpticalSystem method CpCb, lines 432 and 433 use the telescope attenuation in the calculation of throughput:
T = syst['throughput'](lam, WA) / inst['Ns'] \
                * self.attenuation**2               # throughput

It is my understanding from the defintion of telescope attenuation in the ICD, that the attenuation in the equation above should not be squared.

**Comment by ChrisDelaX** [comment]
OpticalSystem.attenuation is the overall attenuation of the optical elements up to the exit pupil (including any reduction due to an image plane mask), cf. Kasdin&Braems2006 paper, Eqn. (2). It is squared because the irradiance I ∝ E^2.  And indeed, this is different from the definition in the ICD. I can 
- either adapt the definition in the ICD to match the eta in Kasdin&Braems (and also adapt the definition in the modules documentation)
- or remove the power 2, and keep the attenuation definition as it is.

**Comment by dsavransky** [comment]
Let's stick with the current ICD definition and kill the power of 2.

**Comment by ChrisDelaX** [comment]
Done.
