### ISSUE TITLE
Prototype next_target allocate time if no available target doubles each successive execution

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#91]
In Prototype survey simulation in the next_target method near the end in "# 6/ choose best target from remaining", each successive use of the TK.allocate_time will double the wait time value. There should be a logical amount of time to wait (suggest next target exiting a keepout or until the mission time runs out)

**Comment by dsavransky** [comment]
This is by design.  The allocation is TK.waitTime*TK.waitMultiple**cnt where cnt is iterated each time you fail to pick a target.  This prevents the simulation from eating up too much time when there are too few available targets by geometrically increasing the time skipped. However, if waitMultiple is set to 1, then the same amount of time will be allocated between each skip.
